### ISSUE TITLE
confusion about description for "run"

### ISSUE THREAD

**Issue by foozmeat** [Kamilcuk/nomad-tools#2]
The help text for `run`  says `Run a Nomad job and then act like started mode.` and the help text for `started` says `Watch a Nomad job until the job is started.` however `run` does not exit until the job is finished but `started` exits as soon as the job is started. Am I misunderstanding? It seems that `run` should indicate that it only exits when the job finishes.

**Comment by Kamilcuk** [comment]
Ne, you're right, I'll fix that. `run` should be like `docker-compose run` or `docker run` - it should start, run, then stop.
