### ISSUE TITLE
Not seeing log output but some kind of template output

### ISSUE THREAD

**Issue by jamespanic** [Kamilcuk/nomad-tools#20]
```
watch> INFO + nomad job run -detach -verbose job.nomad
watch> INFO Job registration successful
watch> INFO Evaluation ID: 0cc22349-e2b0-7647-8a4f-bc95d2009f28
watch> INFO Watching job xxx/main@default until it is started
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
{mark}>{task + '>' if task else ''}{message}
```

nomad version: 1.8.1

**Comment by Kamilcuk** [comment]
Hi. What is the full command line that you used? What python version are you using? What is the output of `nomadtools --version`? I think I released one version with this bug... please update.

**Comment by jamespanic** [comment]
I'm using 0.5.0 but I was running it like this

`nomadtools watch --log-format="{mark}>{task + '>' if task else ''}{message}" start job.nomad` but I don't recall why I was using the custom log format so I removed it and it seems to be working fine.

**Comment by Kamilcuk** [comment]
Hi, that's on me. I changed from python .format() to jinja2 templating. I added --log-nospace and --log-j that should get this look.
