### ISSUE TITLE
nomad-watch returns a failure when one job isn't reallocated but others are

### ISSUE THREAD

**Issue by foozmeat** [Kamilcuk/nomad-tools#4]
We have lots of jobs that deploy redis but usually those allocations aren't cycled when the web job is deployed. Here's what that looks like

![CleanShot 2023-11-13 at 12 59 36@2x](https://github.com/Kamilcuk/nomad-tools/assets/419456/9f047f41-7858-40f6-9bf6-19db6a59fc7b)

nomad-watch is marking these deployments as failed I think because its not seeing that redis was allocated. Happy to provide logs if needed.

```
deploy>redis Canaries=0/0 Placed=1 Desired=1 Healthy=1 Unhealthy=0 Deployment completed successfully
deploy>web Canaries=0/0 Placed=1 Desired=1 Healthy=1 Unhealthy=0 Deployment completed successfully
deploy>rq Canaries=0/0 Placed=1 Desired=1 Healthy=1 Unhealthy=0 Deployment completed successfully
nomad-watch>1079> ERROR Job web/stage#33@default group 'redis' started 0 allocation out of 1.
```

**Comment by Kamilcuk** [comment]
Hi. I am not able to reproduce. Please post the job spec. What nomad version do you have? Thanks!

**Comment by Kamilcuk** [comment]
So I created a unit test for this and looks fine and not able to reproduce.
